# Generated by Django 3.2.7 on 2021-10-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
